doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_sqlite'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: 'sqlite:///%kernel.project_dir%/db.db'
    orm:
        dql:
            string_functions:
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            App\Domain\Model:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/ORM/Mapping/Domain/Model'
                prefix: 'App\Domain\Model'
